language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go build && ./fzp --help
  - go test -v -covermode="count" -coverprofile="go_fzp.cover" github.com/paulvollmer/fzp/go
  - $HOME/gopath/bin/goveralls -coverprofile="go_fzp.cover" -service=travis-ci


#  -covermode=count -coverprofile=coverage.out
# - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
