language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go build && ./fzp --help
  - go test -v ./... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -service=travis-ci
